apiVersion: v1
kind: ConfigMap
metadata:
  name: kuber-cm
data:
  additional.properties: |
    server.port=8000
    logging.level.web=TRACE
    spring.datasource.url=jdbc:postgresql://postgres-service.database:5432/otus
    spring.datasource.username=${POSTGRES_USER}
    spring.datasource.password=${POSTGRES_PASSWORD}
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.database=postgresql
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
  init.sql: |
    SELECT '
      CREATE DATABASE otus
      WITH
        OWNER = root
        ENCODING = "UTF8"
        LC_COLLATE = "en_US.utf8"
        LC_CTYPE = "en_US.utf8"
        LOCALE_PROVIDER = "libc"
        TABLESPACE = pg_default
        CONNECTION LIMIT = -1
        IS_TEMPLATE = False;'
    WHERE NOT EXISTS (SELECT * FROM pg_database WHERE datname = 'otus');
    \gexec
    
    \connect otus;
    
    CREATE SEQUENCE IF NOT EXISTS public.user_seq
      INCREMENT 1
      START 1
      MINVALUE 1
      MAXVALUE 9223372036854775807
      CACHE 1;
    
    ALTER SEQUENCE IF EXISTS public.user_seq
      OWNER TO root;
    
    CREATE TABLE IF NOT EXISTS public."user" (
      id bigint NOT NULL DEFAULT nextval('user_seq'::regclass),
      username character varying(256) COLLATE pg_catalog."default",
      firstname character varying(200) COLLATE pg_catalog."default",
      lastname character varying(200) COLLATE pg_catalog."default",
      email character varying(254) COLLATE pg_catalog."default",
      phone character varying(20) COLLATE pg_catalog."default",
      CONSTRAINT user_pkey PRIMARY KEY (id)
    );
    
    ALTER TABLE IF EXISTS public."user" OWNER to root;