apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
  clusterIP: None
  selector:
    {{- include "postgres.labels" . | nindent 4 }}