apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: auth
  labels:
    app: auth-svc
spec:
  selector:
    env: prod
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8000
  type: LoadBalancer