openapi: 3.0.0
info:
  description: |
    This is simple client API
  version: "1.0.0"
  title: User Service
servers:
  - description: Example Server
    url: http://arch.homework:8000/
tags:
  - name: user
    description: Operations about user
paths:
  /user:
    parameters:
      - in: header
        name: X-User-ID
        schema:
          type: string
        required: true
      - in: header
        name: X-User-Name
        schema:
          type: string
        required: true
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              sample-user:
                summary: Example
                value:
                  firstName: John
                  lastName: Doe
                  email: bestjohn@doe.com
                  phone: '+71002003040'
        description: Created user object
        required: true

    get:
      tags:
        - user
      description: Returns a user based on a single ID, if the user does not have access to the user
      operationId: find user by id
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - user
      description: deletes a single user based on the ID supplied
      operationId: deleteUser
      responses:
        '204':
          description: user deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - user
      description: Update user with User ID supplied
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              sample-user:
                summary: Example
                value:
                  firstName: Julie
                  lastName: Doe
                  email: bestjohn@doe.com
                  phone: '+71004242424'

      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: user updated
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      x-class-extra-annotation: "@jakarta.persistence.Entity 
      @jakarta.persistence.Table(name = \"\\\"user\\\"\")"
      properties:
        id:
          type: integer
          format: int64
          x-field-extra-annotation: "@jakarta.persistence.Id"
        firstName:
          type: string
          x-field-extra-annotation: "@jakarta.persistence.Column(name=\"firstname\")"
        lastName:
          type: string
          x-field-extra-annotation: "@jakarta.persistence.Column(name=\"lastname\")"
        email:
          type: string
          format: email
          x-field-extra-annotation: "@jakarta.persistence.Column(name=\"email\")"
        phone:
          type: string
          format: phone
          x-field-extra-annotation: "@jakarta.persistence.Column(name=\"phone\")"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

  requestBodies:
    UserArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
      description: List of user object
      required: true