{
 "title": "APP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "API Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(http_server_requests_seconds_count[2m])) by (uri), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "API Error Rate  (4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=~\"4..|5..\"}[1m])) /sum(increase(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Success Rate  (non 4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status!~\"4..|5..\"}[1m])) /sum(increase(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \n    sum(rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])) by (le, uri)\n)",
     "legendFormat": "P50 {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.95, \n    sum(rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])) by (le, uri)\n)",
     "legendFormat": "P95 {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.99, \n    sum(rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])) by (le, uri)\n)",
     "legendFormat": "P99 {{uri}}"
    },
    {
     "expr": "histogram_quantile(1, \n    sum(rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])) by (le, uri)\n)",
     "legendFormat": "P100 {{uri}}"
    }
   ]
  },
  { "title": "Nginx Ingress Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Ingress RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Error Rate (4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"4..|5..\"}[1m])) /sum(increase(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Success Rate  (non 4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{status!~\"4..|5..\"}[1m])) /sum(increase(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "P100"
    }
   ]
  },
  { "title": "Pod Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total[5m]) * 100) by (pod)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes) by (pod)"
    }
   ]
  }
 ]
}