apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
    - port: 9187
      name: http-metric
  clusterIP: None
  selector:
    {{- include "postgres.labels" . | nindent 4 }}