apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-ss
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres.labels" . | nindent 6 }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        {{- include "postgres.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: pvc
              mountPath: {{ .Values.volumeMounts.mountPath }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: POSTGRES_PASSWORD
        - name: {{ .Chart.Name }}-exporter
          image: wrouesnel/postgres_exporter:latest
          imagePullPolicy: Always
          ports:
            - name: http-metrics
              containerPort: 9187
              protocol: TCP
          args:
            - "--web.listen-address=:9187"
            - "--auto-discover-databases"
            - "--log.level=debug"
          env:
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: POSTGRES_USER
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: POSTGRES_PASSWORD
            - name: DATA_SOURCE_URI
              value: {{ .Chart.Name }}-service.database:{{ .Values.service.port }}/?sslmode=disable

  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes: [ "{{ .Values.volumeAccessModes }}" ]
        storageClassName: ""
        resources:
          requests:
            storage: {{ .Values.storageSize }}
