apiVersion: v1
kind: ConfigMap
metadata:
  name: order-cm
data:
  order.properties: |
    server.port=8000
    logging.level.web=TRACE
    spring.datasource.url=jdbc:postgresql://postgres-service.database:5432/otus
    spring.datasource.username=${POSTGRES_USER}
    spring.datasource.password=${POSTGRES_PASSWORD}
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.database=postgresql
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
  init.sql: |
    SELECT '
      CREATE DATABASE otus
      WITH
        OWNER = root
        ENCODING = "UTF8"
        LC_COLLATE = "en_US.utf8"
        LC_CTYPE = "en_US.utf8"
        LOCALE_PROVIDER = "libc"
        TABLESPACE = pg_default
        CONNECTION LIMIT = -1
        IS_TEMPLATE = False;'
    WHERE NOT EXISTS (SELECT * FROM pg_database WHERE datname = 'otus');
    \gexec
    
    \connect otus;
    
    --------------------------------------------------------------------------------------------------------------------
    
    CREATE TABLE IF NOT EXISTS public.order
    (
        id         bigserial    PRIMARY KEY ,
        request_id varchar(255) NOT NULL,
        user_id    bigint       NOT NULL,
    
        CONSTRAINT order_request_id_key UNIQUE (request_id)
    );
    
    --------------------------------------------------------------------------------------------------------------------
    
    CREATE TABLE IF NOT EXISTS public.order_product
    (
        id         bigserial     PRIMARY KEY,
        product_id bigint        NOT NULL,
        quantity   integer       NOT NULL,
        amount     decimal(15,2) NOT NULL,
        order_id   bigint        ,
  
        CONSTRAINT order_product_fkey FOREIGN KEY (order_id)
        REFERENCES public.order (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
    );
    
    --------------------------------------------------------------------------------------------------------------------
