apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: order
  labels:
    app: order-svc
spec:
  selector:
    env: prod
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8000
  type: LoadBalancer